Update Profile README
metakgp/.github pull request #1
Opened 2023-08-25 08:22 UTC by chirag-ghosh

- [ ] add about
- [x] add cover image
- [x] add social links

2023-08-26 21:17 UTC, hargup commented
LGTM

2023-08-26 21:17 UTC, hargup submitted a review, later dismissed
LGTM

2023-08-26 22:31 UTC, proffapt requested changes
Shouldn't it be like..
- Who are we?
- What do we do?

2023-08-26 22:31 UTC, proffapt commented on profile/README.md
> +- Mail - `metakgp@gmail.com`
isko mailto: nahi banana?

2023-08-26 22:31 UTC, proffapt commented on profile/README.md
> +An open community coming together to help solve problems an average KGPian faces in everyday life using tech. Issues can be anything that is related to KGP in general. It is an amalgamation of the [W
```suggestion
An open community coming together to help solve problems an average KGPian faces in everyday life using tech. Issues can be anything that is related to KGP in general. It is an amalgamation of the [Wiki](https://wiki.metakgp.org) and multiple projects which the students have been building over the years.
```

2023-08-26 22:56 UTC, chirag-ghosh commented
> Shouldn't it be like..
> 
> * Who are we?
> * What do we do?

Wanted to define the community as a whole. Can change the phrasing if people think this is more appropriate.

2023-08-26 23:00 UTC, proffapt commented
> > Shouldn't it be like..
> > 
> > * Who are we?
> > * What do we do?
> 
> Wanted to define the community as a whole. Can change the phrasing if people think this is more appropriate.

Got your essence but I feel this is much better way of achieving what you are saying. Using `it` kinda does the opposite 🤔

2023-08-27 09:51 UTC, thealphadollar submitted a review, later dismissed

2023-08-31 18:51 UTC, proffapt approved these changes
LGTM.

2023-08-31 18:53 UTC, rajivharlalka approved these changes

2023-08-31 18:54 UTC, merged